// Standalone contract tests: real progress implementation, in-memory save and
// flag/item adapters. Does not open or modify player profiles.
#include "global.h"
#include "event_data.h"
#include "pokemon_regionalidades_progress.h"
#include <stdio.h>

static struct SaveBlock3 sSave;
struct SaveBlock3 *gSaveBlock3Ptr = &sSave;
static u8 sFlags[65536];
static u16 sVars[65536];
static u32 sItems[ITEMS_COUNT];
u16 gSpecialVar_Result;
u16 gSpecialVar_0x8004, gSpecialVar_0x8005, gSpecialVar_0x8006;
u16 gSpecialVar_0x8007, gSpecialVar_0x8008;
bool8 FlagGet(u16 id) { return sFlags[id]; }
u16 VarGet(u16 id) { return sVars[id]; }
bool32 CheckBagHasItem(enum Item item, u32 count) { return sItems[item] >= count; }
bool32 AddBagItem(enum Item item, u32 count) { sItems[item] += count; return TRUE; }
#define CHECK(expr) do { if (!(expr)) { printf("FAIL line %d: %s\n", __LINE__, #expr); return 1; } } while (0)

int main(void)
{
    // Artificial movement permissions must not fabricate the opening story.
    sFlags[FLAG_SYS_B_DASH] = TRUE;
    sFlags[FLAG_RECEIVED_RUNNING_SHOES] = TRUE;
    PgrProgress_EnsureValid();
    CHECK(!PgrProgress_IsStoryEventComplete(PGW_START_HOENN, PGR_HOENN_STORY_RECEIVED_POKEDEX));
    PgrProgress_ScriptCheckHoennPokedex();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_VISITED_LITTLEROOT_TOWN] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_VISITED_LITTLEROOT_TOWN);
    sFlags[FLAG_RESCUED_BIRCH] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RESCUED_BIRCH);
    sFlags[FLAG_DEFEATED_RIVAL_ROUTE103] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_RIVAL_ROUTE103);
    PgrProgress_ScriptCheckHoennPokedex();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_RECEIVED_POKEDEX_FROM_BIRCH] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_POKEDEX_FROM_BIRCH);
    PgrProgress_ScriptCheckHoennPokedex();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennShoes();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennBrawly();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWallyCatchingTutorial();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptGetHoennPetalburgScottOpportunity();
    CHECK(gSpecialVar_Result == 0);
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_RUNNING_SHOES);
    PgrProgress_ScriptCheckHoennShoes();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWallyCatchingTutorial();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennWallyCatchingTutorial();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptGetHoennPetalburgScottOpportunity();
    CHECK(gSpecialVar_Result == 1);
    PgrProgress_ScriptShouldShowHoennRustboroSchoolScott();
    CHECK(!gSpecialVar_Result);
    sVars[VAR_SCOTT_PETALBURG_ENCOUNTER] = 1;
    PgrProgress_ScriptGetHoennPetalburgScottOpportunity();
    CHECK(gSpecialVar_Result == 2);
    PgrProgress_ScriptShouldShowHoennRustboroSchoolScott();
    CHECK(gSpecialVar_Result);
    sVars[VAR_SCOTT_PETALBURG_ENCOUNTER] = 0;
    PgrProgress_ScriptCheckHoennWallyCatchingTutorial();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennRoxanne();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennBrawly();
    CHECK(gSpecialVar_Result);

    // First migrated Hoenn arc: normal order is accepted once, while later
    // scenes cannot start early or repeat after their canonical flag is set.
    PgrProgress_ScriptCheckHoennDevonGoodsTheft();
    CHECK(!gSpecialVar_Result);
    CHECK(PgrProgress_TryCompleteRegisteredStoryEvent(
        PGW_START_HOENN, PGR_HOENN_STORY_RECOVERED_DEVON_GOODS)
        == PGR_PROGRESS_REQUIREMENTS_NOT_MET);
    CHECK(PgrProgress_TryCompleteRegisteredStoryEvent(
        PGW_START_HOENN, PGR_HOENN_STORY_RETURNED_DEVON_GOODS)
        == PGR_PROGRESS_REQUIREMENTS_NOT_MET);
    sFlags[FLAG_DEFEATED_RUSTBORO_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_RUSTBORO_GYM);
    PgrProgress_ScriptGetHoennPetalburgScottOpportunity();
    CHECK(gSpecialVar_Result == 2);
    PgrProgress_ScriptCheckHoennDevonGoodsTheft();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDevonGoodsRecovery();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEVON_GOODS_STOLEN] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEVON_GOODS_STOLEN);
    PgrProgress_ScriptCheckHoennDevonGoodsTheft();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDevonGoodsRecovery();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEVON_GOODS_STOLEN] = FALSE;
    sFlags[FLAG_RECOVERED_DEVON_GOODS] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RECOVERED_DEVON_GOODS);
    PgrProgress_ScriptCheckHoennDevonGoodsRecovery();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDevonGoodsReturn();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_RETURNED_DEVON_GOODS] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RETURNED_DEVON_GOODS);
    PgrProgress_ScriptCheckHoennDevonGoodsReturn();
    CHECK(!gSpecialVar_Result);

    // The optional Rustboro/Route 104 rival encounter may be approached from
    // either side, but it must not exist before Devon gives the commissions.
    PgrProgress_ScriptShouldShowHoennRustboroRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCanMeetHoennRoute104Rival();
    CHECK(!gSpecialVar_Result);

    // The next delivery chain requires both the prior narrative milestone and
    // the concrete parcel that each character expects to receive.
    CHECK(PgrProgress_TryCompleteRegisteredStoryEvent(
        PGW_START_HOENN, PGR_HOENN_STORY_DELIVERED_STEVEN_LETTER)
        == PGR_PROGRESS_REQUIREMENTS_NOT_MET);
    sFlags[FLAG_RECEIVED_POKENAV] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_POKENAV);
    sVars[VAR_SCOTT_PETALBURG_ENCOUNTER] = 1;
    PgrProgress_ScriptShouldShowHoennRustboroSchoolScott();
    CHECK(!gSpecialVar_Result);
    sVars[VAR_SCOTT_PETALBURG_ENCOUNTER] = 0;
    PgrProgress_ScriptShouldShowHoennRustboroRival();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCanMeetHoennRoute104Rival();
    CHECK(gSpecialVar_Result);
    sVars[VAR_ROUTE104_STATE] = 2;
    PgrProgress_ScriptShouldShowHoennRustboroRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCanMeetHoennRoute104Rival();
    CHECK(gSpecialVar_Result);
    sVars[VAR_BOARD_BRINEY_BOAT_STATE] = 1;
    PgrProgress_ScriptCanMeetHoennRoute104Rival();
    CHECK(!gSpecialVar_Result);
    sVars[VAR_ROUTE104_STATE] = 0;
    sVars[VAR_BOARD_BRINEY_BOAT_STATE] = 0;
    PgrProgress_ScriptCheckHoennStevenLetter();
    CHECK(!gSpecialVar_Result);
    sItems[ITEM_LETTER] = 1;
    PgrProgress_ScriptCheckHoennStevenLetter();
    CHECK(gSpecialVar_Result);
    sItems[ITEM_LETTER] = 0;
    sFlags[FLAG_DELIVERED_STEVEN_LETTER] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DELIVERED_STEVEN_LETTER);
    PgrProgress_ScriptShouldShowHoennRustboroRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCanMeetHoennRoute104Rival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDock();
    CHECK(!gSpecialVar_Result);
    sItems[ITEM_DEVON_PARTS] = 1;
    PgrProgress_ScriptCheckHoennDock();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DOCK_REJECTED_DEVON_GOODS] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DOCK_REJECTED_DEVON_GOODS);
    PgrProgress_ScriptCheckHoennDock();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennStern();
    CHECK(gSpecialVar_Result);
    sItems[ITEM_DEVON_PARTS] = 0;
    sFlags[FLAG_DELIVERED_DEVON_GOODS] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DELIVERED_DEVON_GOODS);
    sVars[VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE] = 1;
    PgrProgress_ScriptGetHoennSlateportScottOpportunity();
    CHECK(gSpecialVar_Result == 1);
    sVars[VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE] = 2;
    PgrProgress_ScriptGetHoennSlateportScottOpportunity();
    CHECK(gSpecialVar_Result == 2);
    sVars[VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE] = 1;
    PgrProgress_ScriptCheckHoennStern();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennRoute110Rival();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennRoute110Rival();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptGetHoennSlateportScottOpportunity();
    CHECK(gSpecialVar_Result == 3);
    sVars[VAR_SLATEPORT_OUTSIDE_MUSEUM_STATE] = 2;
    PgrProgress_ScriptGetHoennSlateportScottOpportunity();
    CHECK(gSpecialVar_Result == 2);
    PgrProgress_ScriptCheckHoennRoute110Rival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennRoute110Rival();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_ALREADY_COMPLETE);

    PgrProgress_ScriptCheckHoennWattson();
    CHECK(!gSpecialVar_Result);

    PgrProgress_ScriptCheckHoennWallyMauville();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_WALLY_MAUVILLE] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_WALLY_MAUVILLE);
    PgrProgress_ScriptGetHoennSlateportScottOpportunity();
    CHECK(gSpecialVar_Result == 3);
    PgrProgress_ScriptCheckHoennWallyMauville();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWattson();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT] = TRUE;
    PgrProgress_ScriptShouldShowHoennVerdanturfScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCanMoveHoennScottToFallarbor();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennFallarborScott();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_MAUVILLE_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_MAUVILLE_GYM);
    PgrProgress_ScriptShouldShowHoennVerdanturfScott();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCanMoveHoennScottToFallarbor();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennFallarborScott();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_HIDE_VERDANTURF_TOWN_SCOTT] = TRUE;
    sFlags[FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT] = FALSE;
    PgrProgress_ScriptShouldShowHoennVerdanturfScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennFallarborScott();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWattson();
    CHECK(!gSpecialVar_Result);

    PgrProgress_ScriptCheckHoennMeteoriteTheft();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMaxieMtChimney();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_MET_ARCHIE_METEOR_FALLS] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_MET_ARCHIE_METEOR_FALLS);
    PgrProgress_ScriptShouldShowHoennVerdanturfScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCanMoveHoennScottToFallarbor();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennFallarborScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMeteoriteTheft();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMaxieMtChimney();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennFlannery();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY);
    PgrProgress_ScriptCheckHoennMaxieMtChimney();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennFlannery();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_LAVARIDGE_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_LAVARIDGE_GYM);
    PgrProgress_ScriptCheckHoennFlannery();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennNorman();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennGoGoggles();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_RECEIVED_GO_GOGGLES] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_GO_GOGGLES);
    PgrProgress_ScriptCheckHoennGoGoggles();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennNorman();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_PETALBURG_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_PETALBURG_GYM);
    PgrProgress_ScriptCheckHoennNorman();
    CHECK(!gSpecialVar_Result);

    PgrProgress_ScriptCheckHoennWeatherInstitute();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennStevenRoute118();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennStevenRoute118();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennStevenRoute118();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWeatherInstitute();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennWeatherInstitute();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennWeatherInstitute();
    CHECK(!gSpecialVar_Result);

    PgrProgress_ScriptCheckHoennDevonScope();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennLilycoveRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennLilycoveScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennRoute119Rival();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennRoute119Rival();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennRoute119Rival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennLilycoveRival();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennLilycoveScott();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_MET_SCOTT_IN_LILYCOVE] = TRUE;
    PgrProgress_ScriptShouldShowHoennLilycoveScott();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_MET_SCOTT_IN_LILYCOVE] = FALSE;
    sFlags[FLAG_MET_RIVAL_LILYCOVE] = TRUE;
    PgrProgress_ScriptShouldShowHoennLilycoveRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDevonScope();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWinona();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_RECEIVED_DEVON_SCOPE] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_DEVON_SCOPE);
    PgrProgress_ScriptCheckHoennDevonScope();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennFortreeGymPath();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_KECLEON_FLED_FORTREE] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_KECLEON_FLED_FORTREE);
    PgrProgress_ScriptCheckHoennFortreeGymPath();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWinona();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_FORTREE_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_FORTREE_GYM);
    PgrProgress_ScriptCheckHoennWinona();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMtPyreOrbTheft();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennMtPyreOrbTheft();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    sFlags[FLAG_MET_RIVAL_LILYCOVE] = FALSE;
    PgrProgress_ScriptShouldShowHoennLilycoveRival();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMtPyreOrbTheft();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSubmarineTheft();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennMagmaHideout();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennMagmaHideout();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennMagmaHideout();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSubmarineTheft();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennSubmarineTheft();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptShouldShowHoennLilycoveScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSubmarineTheft();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSeafloorCavern();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennAquaHideout();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennAquaHideout();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennAquaHideout();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSeafloorCavern();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennTateLiza();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennMossdeepScott();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_MOSSDEEP_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_MOSSDEEP_GYM);
    PgrProgress_ScriptCheckHoennTateLiza();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennMossdeepScott();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennMossdeepScott();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptShouldShowHoennMossdeepScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennMossdeepScott();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_ALREADY_COMPLETE);
    PgrProgress_ScriptCheckHoennMossdeepSpaceCenter();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDiveFromSteven();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_MAGMA_SPACE_CENTER] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_MAGMA_SPACE_CENTER);
    PgrProgress_ScriptCheckHoennMossdeepSpaceCenter();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennDiveFromSteven();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennDiveFromSteven();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennDiveFromSteven();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSeafloorCavern();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennSeafloorCavern();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSeafloorCavern();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWallaceRayquaza();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSootopolisCrisis();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennSootopolisCrisis();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSootopolisCrisis();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWallaceRayquaza();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennWallaceRayquaza();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSkyPillarOpening();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennRayquazaAwakening();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennSkyPillarOpening();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSkyPillarOpening();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennRayquazaAwakening();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennRayquazaAwakening();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSootopolisResolution();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennSootopolisResolution();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennSootopolisResolution();
    CHECK(!gSpecialVar_Result);

    // The final Hoenn chain distinguishes technical HM ownership from
    // Wallace's reward, then protects Victory Road and every League battle.
    PgrProgress_ScriptCheckHoennWaterfallFromWallace();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_SOOTOPOLIS_ARCHIE_MAXIE_LEAVE] = TRUE;
    PgrProgress_ScriptCheckHoennWaterfallFromWallace();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennWaterfallFromWallace();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptCheckHoennJuan();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennEverGrandeScott();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_SOOTOPOLIS_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_SOOTOPOLIS_GYM);
    PgrProgress_ScriptCheckHoennJuan();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptShouldShowHoennEverGrandeScott();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_MET_SCOTT_IN_EVERGRANDE] = TRUE;
    PgrProgress_ScriptShouldShowHoennEverGrandeScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennLeagueAccess();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennWallyVictoryRoad();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_WALLY_VICTORY_ROAD] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_WALLY_VICTORY_ROAD);
    PgrProgress_ScriptCheckHoennWallyVictoryRoad();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennLeagueAccess();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_DEWFORD_GYM] = FALSE;
    CHECK(!PgrProgress_IsStoryEventComplete(
        PGW_START_HOENN, PGR_HOENN_STORY_DEFEATED_BRAWLY));
    PgrProgress_ScriptCheckHoennLeagueAccess();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_DEWFORD_GYM] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_DEWFORD_GYM);
    PgrProgress_ScriptCheckHoennBrawly();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennLeagueAccess();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCompleteHoennLeagueEntry();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    sFlags[FLAG_MET_SCOTT_IN_EVERGRANDE] = FALSE;
    PgrProgress_ScriptShouldShowHoennEverGrandeScott();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptCheckHoennSidney();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_ELITE_4_SIDNEY] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_ELITE_4_SIDNEY);
    PgrProgress_ScriptCheckHoennPhoebe();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_ELITE_4_PHOEBE] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_ELITE_4_PHOEBE);
    PgrProgress_ScriptCheckHoennGlacia();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_ELITE_4_GLACIA] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_ELITE_4_GLACIA);
    PgrProgress_ScriptCheckHoennDrake();
    CHECK(gSpecialVar_Result);
    sFlags[FLAG_DEFEATED_ELITE_4_DRAKE] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_DEFEATED_ELITE_4_DRAKE);
    PgrProgress_ScriptCheckHoennChampion();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptGetHoennSSTidalScottOpportunity();
    CHECK(gSpecialVar_Result == 0);
    PgrProgress_ScriptCanStartHoennBattleFrontierReception();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_IS_CHAMPION] = TRUE;
    PgrProgress_OnLegacyFlagSet(FLAG_IS_CHAMPION);
    CHECK(PgrProgress_IsStoryEventComplete(
        PGW_START_HOENN, PGR_HOENN_STORY_BECAME_CHAMPION));
    PgrProgress_ScriptGetHoennPostgameResearchOpportunity();
    CHECK(gSpecialVar_Result == 1);
    PgrProgress_ScriptCompleteHoennPostgameResearchUpdate();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptGetHoennPostgameResearchOpportunity();
    CHECK(gSpecialVar_Result == 2);
    CHECK(!sFlags[FLAG_SYS_NATIONAL_DEX]);
    PgrProgress_ScriptCanUseHoennSSTidal();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptGetHoennSSTidalScottOpportunity();
    CHECK(gSpecialVar_Result == 0);
    // A generic game-clear flag or an item injected by a development save
    // must not manufacture the ferry's narrative acquisition.
    sFlags[FLAG_SYS_GAME_CLEAR] = TRUE;
    sFlags[FLAG_RECEIVED_SS_TICKET] = TRUE;
    sItems[ITEM_SS_TICKET] = 1;
    PgrProgress_ScriptCanUseHoennSSTidal();
    CHECK(!gSpecialVar_Result);
    PgrProgress_OnLegacyFlagSet(FLAG_RECEIVED_SS_TICKET);
    CHECK(PgrProgress_IsStoryEventComplete(
        PGW_START_HOENN, PGR_HOENN_STORY_RECEIVED_SS_TICKET));
    PgrProgress_ScriptCanUseHoennSSTidal();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptGetHoennSSTidalScottOpportunity();
    CHECK(gSpecialVar_Result == 1);
    PgrProgress_ScriptCanStartHoennBattleFrontierReception();
    CHECK(!gSpecialVar_Result);
    sFlags[FLAG_MET_SCOTT_ON_SS_TIDAL] = TRUE;
    PgrProgress_ScriptCompleteHoennSSTidalScott();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    PgrProgress_ScriptGetHoennSSTidalScottOpportunity();
    CHECK(gSpecialVar_Result == 2);
    PgrProgress_ScriptCanStartHoennBattleFrontierReception();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptHasEnteredHoennBattleFrontier();
    CHECK(!gSpecialVar_Result);
    PgrProgress_ScriptGetHoennScottHouseOpportunity();
    CHECK(gSpecialVar_Result == 0);
    PgrProgress_ScriptCompleteHoennBattleFrontierReception();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    sFlags[FLAG_SYS_FRONTIER_PASS] = TRUE;
    PgrProgress_ScriptHasEnteredHoennBattleFrontier();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptCanStartHoennBattleFrontierReception();
    CHECK(gSpecialVar_Result);
    PgrProgress_ScriptGetHoennScottHouseOpportunity();
    CHECK(gSpecialVar_Result == 1);
    PgrProgress_ScriptCompleteHoennScottHouseWelcome();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    sFlags[FLAG_SCOTT_GIVES_BATTLE_POINTS] = TRUE;
    PgrProgress_ScriptGetHoennScottHouseOpportunity();
    CHECK(gSpecialVar_Result == 2);
    PgrProgress_ScriptGetHoennMeteorFallsStevenOpportunity();
    CHECK(gSpecialVar_Result == 1);
    PgrProgress_ScriptCompleteHoennMeteorFallsSteven();
    CHECK(gSpecialVar_Result == PGR_PROGRESS_COMPLETED);
    sFlags[FLAG_DEFEATED_METEOR_FALLS_STEVEN] = TRUE;
    PgrProgress_ScriptGetHoennMeteorFallsStevenOpportunity();
    CHECK(gSpecialVar_Result == 2);

    // Updating a version-2 record must merge the newly known Hoenn flags
    // without erasing progress already stored for another region.
    gSaveBlock3Ptr->regionalidadesProgress.storyEvents[PGW_START_KANTO][1] = 1u << 5;
    gSaveBlock3Ptr->regionalidadesProgress.version = 2;
    PgrProgress_EnsureValid();
    CHECK(gSaveBlock3Ptr->regionalidadesProgress.version == 24);
    CHECK(PgrProgress_IsStoryEventComplete(PGW_START_KANTO, 37));
    CHECK(PgrProgress_IsStoryEventComplete(
        PGW_START_HOENN, PGR_HOENN_STORY_RETURNED_DEVON_GOODS));
    CHECK(PgrProgress_IsStoryEventComplete(
        PGW_START_HOENN, PGR_HOENN_STORY_COMPLETED_WALLY_CATCHING_TUTORIAL));
    CHECK(!PgrProgress_IsStoryEventComplete((enum PgwStartingRegion)-1, 0));
    puts("PASS: Hoenn prerequisites through the optional Steven challenge and legacy migration");
    return 0;
}
