#!/usr/bin/env python3
"""Generate the native PC Pokemon cry resource map."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess


WRAPPER = r"""
#define TRUE 1
#define FALSE 0
#define MODERN 1
#define TESTING 0
#define PORTABLE 0
#include "config/general.h"
#include "config/pokemon.h"
#include "sound/cry_tables.inc"
"""

CONDITION = re.compile(r"^\s*\.if\s+(.+?)\s*(?:@.*)?$")
ENDIF = re.compile(r"^\s*\.endif\b")
CRY_ENTRY = re.compile(r"^\s*cry\s+(Cry_[A-Za-z0-9_]+)\s*(?:@.*)?$")
CRY_LABEL = re.compile(r"^\s*(Cry_[A-Za-z0-9_]+)::\s*$")
INCBIN = re.compile(r'^\s*\.incbin\s+"([^"]+)"')


def fnv1a64(value: str) -> int:
    result = 0xCBF29CE484222325
    for byte in value.encode("utf-8"):
        result ^= byte
        result = (result * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return result


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        path.touch()
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def preprocess(root: Path, cpp: Path) -> str:
    command = [
        str(cpp),
        "-P",
        f"-I{root / 'include'}",
        f"-I{root}",
        "-",
    ]
    result = subprocess.run(
        command,
        cwd=root,
        input=WRAPPER,
        text=True,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"C preprocessor failed ({result.returncode}):\n{result.stderr}")
    return result.stdout


def evaluate_condition(expression: str) -> bool:
    expression = expression.strip()
    if not re.fullmatch(r"[0-9A-Fa-fxX()=!<>&|+\-*/% \t]+", expression):
        raise ValueError(f"unsupported assembler condition: {expression}")
    expression = expression.replace("&&", " and ").replace("||", " or ")
    expression = re.sub(r"(?<![=!<>])!(?!=)", " not ", expression)
    return bool(eval(expression, {"__builtins__": {}}, {}))


def active_cry_symbols(preprocessed: str) -> list[str]:
    active_stack = [True]
    symbols: list[str] = []

    for line in preprocessed.splitlines():
        match = CONDITION.match(line)
        if match:
            active_stack.append(active_stack[-1] and evaluate_condition(match.group(1)))
            continue
        if ENDIF.match(line):
            if len(active_stack) == 1:
                raise ValueError("unmatched .endif in cry table")
            active_stack.pop()
            continue
        match = CRY_ENTRY.match(line)
        if match and active_stack[-1]:
            symbols.append(match.group(1))

    if len(active_stack) != 1:
        raise ValueError("unterminated .if in cry table")
    if not symbols:
        raise ValueError("no active cries found")
    if len(symbols) != len(set(symbols)):
        raise ValueError("duplicate active cry symbol")
    return symbols


def cry_sources(root: Path) -> dict[str, str]:
    source_file = root / "sound/direct_sound_data.inc"
    result: dict[str, str] = {}
    current_symbol: str | None = None

    for line in source_file.read_text(encoding="utf-8").splitlines():
        match = CRY_LABEL.match(line)
        if match:
            current_symbol = match.group(1)
            continue
        match = INCBIN.match(line)
        if match and current_symbol is not None:
            path = match.group(1)
            if not path.startswith("sound/direct_sound_samples/cries/"):
                raise ValueError(f"unexpected cry source for {current_symbol}: {path}")
            result[current_symbol] = path
            current_symbol = None

    return result


def generate(root: Path, cpp: Path, header: Path, resource_list: Path, makefile: Path) -> None:
    symbols = active_cry_symbols(preprocess(root, cpp))
    sources = cry_sources(root)
    resources: list[dict[str, str]] = []
    hashes: list[int] = []
    assets: list[str] = []

    for symbol in symbols:
        source = sources.get(symbol)
        if source is None:
            raise ValueError(f"active cry has no sample source: {symbol}")
        if not (root / source).is_file() and not (root / source).with_suffix(".wav").is_file():
            raise FileNotFoundError(f"cry source does not exist: {source}")
        name = f"sound/cries/{symbol}"
        resources.append({"name": name, "source": source})
        hashes.append(fnv1a64(name))
        assets.append(source)

    header_lines = [
        "// Generated by tools/pokemon_go_world/generate_cry_resources.py.",
        "// Do not edit by hand.",
        "#ifndef GUARD_GENERATED_PC_CRY_RESOURCES_H",
        "#define GUARD_GENERATED_PC_CRY_RESOURCES_H",
        "",
        "static const u64 sPcCryResourceHashes[] =",
        "{",
    ]
    for value in hashes:
        header_lines.append(f"    UINT64_C({value}),")
    header_lines.extend([
        "};",
        "",
        "STATIC_ASSERT(ARRAY_COUNT(sPcCryResourceHashes) == CRY_COUNT - 1, PcCryResourceCountMismatch)",
        "",
        "#endif // GUARD_GENERATED_PC_CRY_RESOURCES_H",
        "",
    ])

    resource_document = {"format_version": 1, "resources": resources}
    make_lines = [
        "# Generated by tools/pokemon_go_world/generate_cry_resources.py.",
        "PC_CRY_RESOURCE_ASSETS := \\",
    ]
    for index, path in enumerate(sorted(set(assets))):
        continuation = " \\" if index != len(set(assets)) - 1 else ""
        make_lines.append(f"\t{path}{continuation}")
    make_lines.append("")

    write_if_changed(header, "\n".join(header_lines))
    write_if_changed(resource_list, json.dumps(resource_document, indent=2) + "\n")
    write_if_changed(makefile, "\n".join(make_lines))
    print(f"Generated {len(symbols)} active Pokemon cries")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--cpp", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--resource-list", type=Path, required=True)
    parser.add_argument("--makefile", type=Path, required=True)
    args = parser.parse_args()
    generate(
        args.root.resolve(),
        args.cpp.resolve(),
        args.header.resolve(),
        args.resource_list.resolve(),
        args.makefile.resolve(),
    )


if __name__ == "__main__":
    main()
