#!/usr/bin/env python3
"""Generate the PC Pokemon picture resource map from the active config."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess


WRAPPER = r"""
#define TRUE 1
#define FALSE 0
#define MODERN 1
#include "config/general.h"
#include "config/pokemon.h"
#include "config/overworld.h"
#include "data/graphics/pokemon.h"
"""

DECLARATION = re.compile(
    r"const\s+u32\s+"
    r"(gMon(?:FrontPic|BackPic|EggGfx|HatchGfx)_[A-Za-z0-9_]+)"
    r"\[\]\s*=\s*INCGFX_U32\(\"([^\"]+)\",\s*\"([^\"]+)\"\);"
)

FRONT_FALLBACK = "graphics/pokemon/pics/gMonFrontPic_CircledQuestionMark"
BACK_FALLBACK = "graphics/pokemon/pics/gMonBackPic_CircledQuestionMark"


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        path.touch()
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def preprocess(root: Path, cpp: Path) -> str:
    command = [
        str(cpp),
        "-P",
        f"-I{root / 'include'}",
        f"-I{root / 'src'}",
        "-",
    ]
    result = subprocess.run(
        command,
        cwd=root,
        input=WRAPPER,
        text=True,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"C preprocessor failed ({result.returncode}):\n{result.stderr}")
    return result.stdout


def fallback_for(symbol: str) -> str | None:
    if symbol.startswith("gMonBackPic_"):
        return BACK_FALLBACK
    if symbol.startswith("gMonFrontPic_") or symbol.startswith("gMonEggGfx_"):
        return FRONT_FALLBACK
    return None


def generate(root: Path, cpp: Path, header: Path, resource_list: Path, makefile: Path) -> None:
    declarations: dict[str, tuple[str, str]] = {}
    for match in DECLARATION.finditer(preprocess(root, cpp)):
        symbol, source, extension = match.groups()
        value = (source, extension)
        if symbol in declarations and declarations[symbol] != value:
            raise ValueError(f"conflicting active definitions for {symbol}")
        declarations[symbol] = value

    if FRONT_FALLBACK.rsplit("/", 1)[1] not in declarations:
        raise ValueError("front picture fallback is missing from active graphics")
    if BACK_FALLBACK.rsplit("/", 1)[1] not in declarations:
        raise ValueError("back picture fallback is missing from active graphics")

    resources: list[dict[str, str]] = []
    entries: list[tuple[str, str, str | None]] = []
    asset_paths: list[str] = []
    for symbol, (source, extension) in sorted(declarations.items()):
        name = f"graphics/pokemon/pics/{symbol}"
        generated_source = f"build/assets/{source}{extension}"
        if not (root / source).is_file():
            raise FileNotFoundError(f"Pokemon picture source does not exist: {root / source}")
        resources.append({"name": name, "source": generated_source})
        entries.append((symbol, name, fallback_for(symbol)))
        asset_paths.append(generated_source)

    header_lines = [
        "// Generated by tools/pokemon_go_world/generate_pokemon_resources.py.",
        "// Do not edit by hand.",
        "#ifndef GUARD_GENERATED_PC_POKEMON_RESOURCES_H",
        "#define GUARD_GENERATED_PC_POKEMON_RESOURCES_H",
        "",
        "#include \"pokemon_resources.h\"",
        "#include \"resource_pack.h\"",
        "",
        "struct PcPokemonPicResource",
        "{",
        "    const void *compiledData;",
        "    const char *name;",
        "    const char *fallbackName;",
        "};",
        "",
        "static const struct PcPokemonPicResource sPcPokemonPicResources[] =",
        "{",
    ]
    for symbol, name, fallback in entries:
        fallback_value = f'\"{fallback}\"' if fallback is not None else "NULL"
        header_lines.append(f'    {{ {symbol}, "{name}", {fallback_value} }},')
    header_lines.extend([
        "};",
        "",
        "void *LoadExternalPokemonPic(const void *compiledData, u64 *sizeOut)",
        "{",
        "    u32 i;",
        "",
        "    for (i = 0; i < ARRAY_COUNT(sPcPokemonPicResources); i++)",
        "    {",
        "        const struct PcPokemonPicResource *resource = &sPcPokemonPicResources[i];",
        "        void *data;",
        "",
        "        if (resource->compiledData != compiledData)",
        "            continue;",
        "        data = ResourcePack_Load(resource->name, sizeOut);",
        "        if (data == NULL && resource->fallbackName != NULL",
        "         && strcmp(resource->name, resource->fallbackName) != 0)",
        "            data = ResourcePack_Load(resource->fallbackName, sizeOut);",
        "        return data;",
        "    }",
        "    if (sizeOut != NULL)",
        "        *sizeOut = 0;",
        "    DBGPRINTF(\"Pokemon resource: unknown compiled picture identifier %p\\n\", compiledData);",
        "    return NULL;",
        "}",
        "",
        "#endif // GUARD_GENERATED_PC_POKEMON_RESOURCES_H",
        "",
    ])

    resource_document = {
        "format_version": 1,
        "resources": resources,
    }
    make_lines = [
        "# Generated by tools/pokemon_go_world/generate_pokemon_resources.py.",
        "PC_POKEMON_RESOURCE_ASSETS := \\",
    ]
    for index, path in enumerate(asset_paths):
        continuation = " \\" if index != len(asset_paths) - 1 else ""
        make_lines.append(f"\t{path}{continuation}")
    make_lines.append("")

    write_if_changed(header, "\n".join(header_lines))
    write_if_changed(resource_list, json.dumps(resource_document, indent=2) + "\n")
    write_if_changed(makefile, "\n".join(make_lines))
    print(f"Generated {len(resources)} active Pokemon picture resources")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--cpp", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--resource-list", type=Path, required=True)
    parser.add_argument("--makefile", type=Path, required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    generate(root, args.cpp.resolve(), args.header.resolve(),
             args.resource_list.resolve(), args.makefile.resolve())


if __name__ == "__main__":
    main()
