#!/usr/bin/env python3
"""Generate external resource metadata for active map tileset animations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess


CPP_DEFINES = (
    "-DMODERN=1",
    "-DTESTING=0",
    "-DEMERALD",
    "-DPORTABLE",
    "-DPC_TILESET_ANIM_RESOURCE_SCAN",
    "-DNONMATCHING",
    "-DUBFIX",
    "-DPLATFORM_SDL2",
    "-DRENDERER_EASY_DRAW",
)

GFX_DECLARATION = re.compile(
    r"(?:static\s+)?const\s+u16\s+([A-Za-z0-9_]+)\[\]\s*=\s*"
    r"INCGFX_U16\(\s*\"([^\"]+)\"\s*,\s*\"([^\"]+)\""
    r"(?:\s*,\s*\"([^\"]*)\")?\s*\)\s*;",
    re.DOTALL,
)
BIN_DECLARATION = re.compile(
    r"(?:static\s+)?const\s+u16\s+([A-Za-z0-9_]+)\[\]\s*=\s*"
    r"INCBIN_U16\((.*?)\)\s*;",
    re.DOTALL,
)
QUOTED_ARGUMENT = re.compile(r'\"([^\"]+)\"')


def fnv1a64(value: str) -> int:
    result = 0xCBF29CE484222325
    for byte in value.encode("utf-8"):
        result ^= byte
        result = (result * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return result


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        path.touch()
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def arguments_as_path(arguments: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in arguments)


def generated_asset(source: str, extension: str, arguments: str) -> str:
    return f"build/assets/{source}{arguments_as_path(arguments)}{extension}"


def preprocess(root: Path, cpp: Path) -> str:
    command = [
        str(cpp),
        "-P",
        f"-I{root / 'include'}",
        f"-I{root / 'src'}",
        f"-I{root}",
        *CPP_DEFINES,
        "-std=gnu17",
        str(root / "src" / "tileset_anims.c"),
    ]
    result = subprocess.run(
        command,
        cwd=root,
        text=True,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"C preprocessor failed ({result.returncode}):\n{result.stderr}")
    return result.stdout


def add_unique(mapping: dict[str, tuple[str, ...]], symbol: str, sources: tuple[str, ...]) -> None:
    previous = mapping.get(symbol)
    if previous is not None and previous != sources:
        raise ValueError(f"conflicting active definitions for {symbol}")
    mapping[symbol] = sources


def generate(root: Path, cpp: Path, header: Path, resource_list: Path, makefile: Path) -> None:
    source_text = preprocess(root, cpp)
    declarations: dict[str, tuple[str, ...]] = {}
    assets: set[str] = set()

    for match in GFX_DECLARATION.finditer(source_text):
        symbol, source, extension, arguments = match.groups()
        if not (root / source).is_file():
            raise FileNotFoundError(f"tileset animation source does not exist: {source}")
        asset = generated_asset(source, extension, arguments or "")
        add_unique(declarations, symbol, (asset,))
        assets.add(asset)

    for match in BIN_DECLARATION.finditer(source_text):
        symbol, arguments = match.groups()
        sources = tuple(QUOTED_ARGUMENT.findall(arguments))
        if not sources:
            raise ValueError(f"tileset animation binary has no sources: {symbol}")
        for source in sources:
            if not (root / source).is_file():
                raise FileNotFoundError(f"tileset animation binary does not exist: {source}")
            assets.add(source)
        add_unique(declarations, symbol, sources)

    if not declarations:
        raise ValueError("no active tileset animation frames found")

    resources: list[dict[str, object]] = []
    table_entries: list[tuple[str, str]] = []
    for symbol, sources in sorted(declarations.items()):
        name = f"tileset_anims/{symbol}"
        resource: dict[str, object] = {"name": name}
        if len(sources) == 1:
            resource["source"] = sources[0]
        else:
            resource["sources"] = list(sources)
        resources.append(resource)
        table_entries.append((symbol, name))

    lines = [
        "// Generated by tools/pokemon_go_world/generate_tileset_anim_resources.py.",
        "// Do not edit by hand.",
        "#ifndef GUARD_GENERATED_PC_TILESET_ANIM_RESOURCES_H",
        "#define GUARD_GENERATED_PC_TILESET_ANIM_RESOURCES_H",
        "",
        "#include \"resource_pack.h\"",
        "",
        "struct PcTilesetAnimResource",
        "{",
        "    const u16 *compiledData;",
        "    u64 hash;",
        "    const u16 *resolvedData;",
        "    u64 size;",
        "    bool8 attempted;",
        "    bool8 reportedInvalid;",
        "};",
        "",
        "static struct PcTilesetAnimResource sPcTilesetAnimResources[] =",
        "{",
    ]
    for symbol, name in table_entries:
        lines.append(f"    {{ {symbol}, UINT64_C({fnv1a64(name)}) }},")
    lines.extend([
        "};",
        "",
        "static const u16 sMissingTilesetAnimFrame[2048] = {0};",
        "",
        "const u16 *ResolveTilesetAnimFrame(const u16 *compiledData, u16 requiredSize)",
        "{",
        "    u32 i;",
        "",
        "    for (i = 0; i < ARRAY_COUNT(sPcTilesetAnimResources); i++)",
        "    {",
        "        struct PcTilesetAnimResource *resource = &sPcTilesetAnimResources[i];",
        "",
        "        if (resource->compiledData != compiledData)",
        "            continue;",
        "        if (!resource->attempted)",
        "        {",
        "            resource->resolvedData = ResourcePack_GetByHash(resource->hash, &resource->size);",
        "            resource->attempted = TRUE;",
        "        }",
        "        if (resource->resolvedData != NULL && resource->size >= requiredSize)",
        "            return resource->resolvedData;",
        "        if (!resource->reportedInvalid)",
        "        {",
        "            DBGPRINTF(\"Tileset animation: identifier %p is missing or too small\\n\", compiledData);",
        "            resource->reportedInvalid = TRUE;",
        "        }",
        "        return sMissingTilesetAnimFrame;",
        "    }",
        "",
        "    DBGPRINTF(\"Tileset animation: unknown compiled identifier %p\\n\", compiledData);",
        "    return sMissingTilesetAnimFrame;",
        "}",
        "",
        "#endif // GUARD_GENERATED_PC_TILESET_ANIM_RESOURCES_H",
        "",
    ])

    resource_document = {"format_version": 1, "resources": resources}
    make_lines = [
        "# Generated by tools/pokemon_go_world/generate_tileset_anim_resources.py.",
        "PC_TILESET_ANIM_RESOURCE_ASSETS := \\",
    ]
    sorted_assets = sorted(assets)
    for index, path in enumerate(sorted_assets):
        continuation = " \\" if index != len(sorted_assets) - 1 else ""
        make_lines.append(f"\t{path}{continuation}")
    make_lines.append("")

    write_if_changed(header, "\n".join(lines))
    write_if_changed(resource_list, json.dumps(resource_document, indent=2) + "\n")
    write_if_changed(makefile, "\n".join(make_lines))
    print(f"Generated {len(declarations)} active tileset animation frames")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--cpp", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--resource-list", type=Path, required=True)
    parser.add_argument("--makefile", type=Path, required=True)
    args = parser.parse_args()
    generate(
        args.root.resolve(),
        args.cpp.resolve(),
        args.header.resolve(),
        args.resource_list.resolve(),
        args.makefile.resolve(),
    )


if __name__ == "__main__":
    main()
