#!/usr/bin/env python3
"""Replace PC map layout binaries with resource-pack placeholders."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re


LABEL_PATTERN = re.compile(r"^([A-Za-z0-9_]+)::$")
INCBIN_PATTERN = re.compile(r'^(\s*)\.incbin\s+"([^"]+)"\s*$')


def fnv1a64(value: str) -> int:
    result = 0xCBF29CE484222325
    for byte in value.encode("utf-8"):
        result ^= byte
        result = (result * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return result


def write_text_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        path.touch()
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def parse_layouts(root: Path, source: Path) -> tuple[str, list[dict[str, object]], int]:
    output_lines: list[str] = []
    resources: list[dict[str, object]] = []
    current_label: str | None = None
    layout_count = 0

    for line in source.read_text(encoding="utf-8").splitlines():
        label_match = LABEL_PATTERN.match(line.strip())
        if label_match:
            current_label = label_match.group(1)
            if (current_label.endswith("_Layout")
                    and not current_label.endswith("_Border")
                    and not current_label.endswith("_Blockdata")):
                layout_count += 1

        incbin_match = INCBIN_PATTERN.match(line)
        if incbin_match:
            if current_label is None or not (
                    current_label.endswith("_Layout_Border")
                    or current_label.endswith("_Layout_Blockdata")):
                raise ValueError(f"unexpected layout incbin without a resource label: {line}")
            relative_path = Path(incbin_match.group(2))
            asset_path = root / relative_path
            if not asset_path.is_file():
                raise ValueError(f"layout resource does not exist: {relative_path}")
            size = asset_path.stat().st_size
            if size == 0 or size % 2 != 0:
                raise ValueError(f"layout resource has an invalid size: {relative_path} ({size})")
            name = f"map_layouts/{current_label}"
            resources.append({
                "label": current_label,
                "name": name,
                "source": relative_path.as_posix(),
                "size": size,
                "hash": fnv1a64(name),
            })
            output_lines.append(f"{incbin_match.group(1)}.space 4")
        else:
            output_lines.append(line)

    if layout_count == 0 or len(resources) != layout_count * 2:
        raise ValueError(
            f"layout/resource count mismatch: layouts={layout_count}, resources={len(resources)}"
        )
    labels = [str(resource["label"]) for resource in resources]
    if len(labels) != len(set(labels)):
        raise ValueError("duplicate layout resource label")
    return "\n".join(output_lines) + "\n", resources, layout_count


def generate(root: Path, source: Path, output_include: Path, header: Path,
             resource_list: Path, makefile: Path) -> None:
    assembly, resources, layout_count = parse_layouts(root, source)
    header_lines = [
        "// Generated by tools/pokemon_go_world/generate_map_layout_resources.py.",
        "// Do not edit by hand.",
        "#ifndef GUARD_GENERATED_PC_MAP_LAYOUT_RESOURCES_H",
        "#define GUARD_GENERATED_PC_MAP_LAYOUT_RESOURCES_H", "",
        "#include <string.h>",
        "#include \"map_layout_resources.h\"",
        "#include \"malloc.h\"",
        "#include \"resource_pack.h\"", "",
    ]
    for resource in resources:
        header_lines.append(f"extern const u8 {resource['label']}[];")
    header_lines.extend([
        "", "struct PcMapLayoutResource", "{",
        "    const void *compiledData;", "    u64 hash;", "    u32 expectedSize;",
        "    const void *resolvedData;", "    bool8 attempted;", "    bool8 reportedInvalid;",
        "};", "", "static struct PcMapLayoutResource sPcMapLayoutResources[] =", "{",
    ])
    for resource in resources:
        header_lines.append(
            f"    {{ {resource['label']}, UINT64_C({resource['hash']}), {resource['size']} }},"
        )
    header_lines.extend([
        "};", "", f"static struct MapLayout sPcResolvedMapLayouts[{layout_count}];",
        f"static bool8 sPcResolvedMapLayoutValid[{layout_count}];",
        "static const u16 sPcMissingMapWord[1] = {0};", "",
        "static const u16 *ResolvePcMapLayoutData(const void *compiledData)", "{",
        "    u32 i;", "", "    for (i = 0; i < ARRAY_COUNT(sPcMapLayoutResources); i++)", "    {",
        "        struct PcMapLayoutResource *resource = &sPcMapLayoutResources[i];",
        "        u64 size = 0;", "        const void *data;", "",
        "        if (resource->compiledData != compiledData)", "            continue;",
        "        if (!resource->attempted)", "        {", "            resource->attempted = TRUE;",
        "            data = ResourcePack_GetByHash(resource->hash, &size);",
        "            if (data != NULL && size == resource->expectedSize)",
        "                resource->resolvedData = data;", "            else", "            {",
        "                resource->resolvedData = AllocZeroed(resource->expectedSize);",
        "                if (resource->resolvedData == NULL)",
        "                    resource->resolvedData = sPcMissingMapWord;",
        "                DBGPRINTF(\"Map layout resource: hash %llu is missing or invalid; using a zeroed fallback\\n\", resource->hash);",
        "                resource->reportedInvalid = TRUE;", "            }", "        }",
        "        return resource->resolvedData;", "    }", "",
        "    DBGPRINTF(\"Map layout resource: unknown compiled identifier %p\\n\", compiledData);",
        "    return sPcMissingMapWord;", "}", "",
        "const struct MapLayout *ResolvePcMapLayout(u16 mapLayoutId, const struct MapLayout *compiledLayout)", "{",
        "    u32 index;", "    struct MapLayout *resolvedLayout;", "",
        "    if (mapLayoutId == 0 || mapLayoutId > ARRAY_COUNT(sPcResolvedMapLayouts))",
        "        return compiledLayout;", "    index = mapLayoutId - 1;",
        "    if (sPcResolvedMapLayoutValid[index])", "        return &sPcResolvedMapLayouts[index];", "",
        "    resolvedLayout = &sPcResolvedMapLayouts[index];",
        "    memcpy(resolvedLayout, compiledLayout, sizeof(*resolvedLayout));",
        "    resolvedLayout->border = ResolvePcMapLayoutData(compiledLayout->border);",
        "    resolvedLayout->map = ResolvePcMapLayoutData(compiledLayout->map);",
        "    sPcResolvedMapLayoutValid[index] = TRUE;", "    return resolvedLayout;", "}", "",
        "#endif // GUARD_GENERATED_PC_MAP_LAYOUT_RESOURCES_H", "",
    ])

    resource_document = {
        "format_version": 1,
        "resources": [
            {"name": resource["name"], "source": resource["source"]}
            for resource in resources
        ],
    }
    make_lines = [
        "# Generated by tools/pokemon_go_world/generate_map_layout_resources.py.",
        "PC_MAP_LAYOUT_RESOURCE_ASSETS := \\",
    ]
    sources = [str(resource["source"]) for resource in resources]
    for index, asset in enumerate(sources):
        continuation = " \\" if index + 1 < len(sources) else ""
        make_lines.append(f"\t{asset}{continuation}")
    make_lines.append("")

    write_text_if_changed(output_include, assembly)
    write_text_if_changed(header, "\n".join(header_lines))
    write_text_if_changed(resource_list, json.dumps(resource_document, indent=2) + "\n")
    write_text_if_changed(makefile, "\n".join(make_lines))
    total_size = sum(int(resource["size"]) for resource in resources)
    print(f"Generated {layout_count} map layouts ({len(resources)} resources, {total_size} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output-include", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--resource-list", type=Path, required=True)
    parser.add_argument("--makefile", type=Path, required=True)
    args = parser.parse_args()
    generate(
        args.root.resolve(), args.source.resolve(), args.output_include.resolve(),
        args.header.resolve(), args.resource_list.resolve(), args.makefile.resolve(),
    )


if __name__ == "__main__":
    main()
